//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mandofashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int MaBV { get; set; }
        public string TenBV { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string TaiKhoanTV { get; set; }
        public string TomTatND { get; set; }
        public string HinhDD { get; set; }
        public string NoiDungBV { get; set; }
        public bool DaDuyet { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
