//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mandofashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.ChiTietDHs = new HashSet<ChiTietDH>();
        }
    
        public int MaSP { get; set; }
        public int MaLoai { get; set; }
        public string TenSP { get; set; }
        public string DuongDanAnh { get; set; }
        public string DuongDanAnh1 { get; set; }
        public string DuongDanAnh2 { get; set; }
        public string DuongDanAnh3 { get; set; }
        public string TomTatND { get; set; }
        public System.DateTime NgayDangSP { get; set; }
        public string TaiKhoanTV { get; set; }
        public int GiaBan { get; set; }
        public string DonVi { get; set; }
        public string KhuyenMai { get; set; }
        public int SoLuong { get; set; }
        public string NoiDungSP { get; set; }
        public bool KiemDuyet { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> LuotMua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSanPham> AnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
